config: [configs/dataset.yaml, configs/model.yaml, configs/training.yaml]
device: cpu
export_config: yes
testing:
    dataset:
        pickle_path: dataset/all_jets_test_4D_100_percent.pkl
    step: 100
    step_size: 10
training:
    dataset:
        pickle_path: dataset/all_jets_train_4D_100_percent.pkl
    export_saved_model_dir: saved_model
    learning_rate: 0.001
    logdir: logdir
    num_steps: 100000
    batch_size: 8
    loss: root_mean_squared_error
    checkpoint_step: 999
    checkpoint_folder: /home/rick/HEP/checkpoints/ckpt
export_config_path: /home/rick/HEP/biggie_config.yaml
models:
    type: vanilla
    vanilla:
        architecture:
            encoder:
                num_units: [100, 50, 3]
            decoder:
                num_units: [50, 100, 4]
    residual:
        architecture:
            encoder:
                num_units: [100, 50, 3]
            decoder:
                num_units: [50, 100, 4]
        weight: 0.01
dataset:
    records_path: /home/rick/HEP/cache
    repeat: -1
    shuffle: yes
