config: [biggie_config.yaml, configs/training.yaml]
device: cpu
export_config: yes
training:
    export_saved_model_dir: final_model
    learning_rate: 0.001
    batch_size: 64
    num_steps: 50000
    loss: root_mean_squared_error
    checkpoint_step: 1999
    checkpoint_folder: /home/rick/HEP/checkpoints/ckpt
    dataset:
        pickle_path: dataset/all_jets_train_4D_100_percent.pkl
    logdir: logdir
export_config_path: /home/rick/HEP/biggie_config.yaml
testing:
    step: 100
    step_size: 10
    dataset:
        pickle_path: dataset/all_jets_test_4D_100_percent.pkl
models:
    type: vanilla
    vanilla:
        architecture:
            encoder:
                num_units: [100, 50, 3]
            decoder:
                num_units: [50, 100, 4]
    residual:
        architecture:
            encoder:
                num_units: [100, 50, 3]
            decoder:
                num_units: [50, 100, 4]
        weight: 0.01
dataset:
    records_path: /home/rick/HEP/cache
    repeat: -1
    shuffle: yes
