config: [configs/dataset.yaml, configs/model.yaml, configs/training.yaml]
dataset:
    testing:
        pickle_path: dataset/all_jets_test_4D_100_percent.pkl
        batch_size: 64
        repeat: -1
    training:
        pickle_path: dataset/all_jets_train_4D_100_percent.pkl
        batch_size: 64
        repeat: -1
    records_path: cache/
    shuffle: yes
device: cpu
export_config: yes
model:
    type: vanilla
training:
    export_saved_model_dir: final_saved_model
    learning_rate: 0.001
    logdir: logdir
    num_steps: 50000
    loss: root_mean_squared_error
    checkpoint_step: 1999
    checkpoint_folder: checkpoints/ckpt
export_config_path: biggie_config.yaml
testing:
    step: 100
    step_size: 10
models:
    type: vanilla
    vanilla:
        architecture:
            encoder:
                num_units:
                - 200
                - 100
                - 50
                - 3
            decoder:
                num_units:
                - 50
                - 100
                - 200
                - 4
    residual:
        architecture:
            encoder:
                num_units: [100, 50, 3]
            decoder:
                num_units: [50, 100, 4]
        weight: 0.01
