export_config_path: "/home/rick/HEP/biggie_config.yaml"
training:
  batch_size: 64
  num_steps: 50000
  learning_rate: !!float 1e-1
  loss: "root_mean_squared_error"
  checkpoint_step: 1999
  checkpoint_folder: '/home/rick/HEP/checkpoints/ckpt'
testing:
  step: 100
  step_size: 10
